### ISSUE TITLE
Logic check_subid.yml

### ISSUE THREAD

**Issue by kymcharlesworth-srg** [ikke-t/podman-container-systemd#24]
Logic in two lines in check_subid.yml appears to be failing:
_when: not uid_line_found.matched and container_run_as_user != 'root'_ 
_when: not gid_line_found.matched and container_run_as_group != 'root'_ 

Change the order around to fix:
_when: container_run_as_user != 'root' and not uid_line_found.matched_
_when: container_run_as_group != 'root' and not gid_line_found.matched_

The Register Variables _uid_line_found_ and _gid_line_found_ do not have a '_matched_' attribute if these tasks are skipped (container_run_as_user = 'root'). This causes a fatal error when Ansible tries to test the '_matched_' attribute (left-hand side of the _and_) when checking the _/etc/subuid_ and _/etc/subgid_ files.

Group fatal is below:
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'not gid_line_found.matched and container_run_as_group != 'root'' failed. The error was: error while evaluating conditional (not gid_line_found.matched and container_run_as_group != 'root'): 'dict object' has no attribute 'matched'\n\nThe error appears to be in '/home/ec2-user/.ansible/roles/podman_container_systemd/tasks/check_subid.yml': line 26, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: ensure group is in subgid file, if it was missing\n  ^ here\n"}

This issue started happening this morning after many weeks of working fine but the issue has been confirmed against two independent systems.

**Comment by ikke-t** [comment]
Thanks for quick feedback and fix. I committed it in. After long time I sat down last night and pulled in change requests, and this came in from one of them.
