### ISSUE TITLE
What is container_pod_yaml use for?

### ISSUE THREAD

**Issue by flyemsafe** [ikke-t/podman-container-systemd#39]
I was looking to see if I can adopt the role to run a pod with multiple instances based on the same image and came across the **container_pod_yaml**. Where is it defined and what is it used for?

**Comment by ikke-t** [comment]
I haven't used it in long time, but I recall you had to put it in place in your own tasks before calling  this role. See this https://redhatnordicssa.github.io/ansible-podman-containers-2

**Comment by flyemsafe** [comment]
Thanks.
